import Head from "next/head";
import styles from "../styles/Home.module.css";
export default function Page() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next v13 App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Home Page</p>
    </div>
  );
}
